'use strict'
define(function(require) {
  let system = require('draw/system')
  let consoleOut = require('console')
  let {evalParamFrame} = require('player/eval-param')
  let {unwrapValue} = require('draw/visualsynth/shader-node')
  let {colour} = require('draw/colour')

  // Lookup textures generated by sampling a limut expression over the unit domain: the data
  // behind tex1d/tex2d/tex3d. Sampling (pure JS) is kept separate from the GL upload so it can
  // be tested without a GL context, the same split codegen.js keeps.

  let defaultSizes = {1: 256, 2: 64, 3: 16}
  let maxTexels = 1 << 20 // A 3d lut is size^3, so a fat size param can be ruinous: cap it

  // How many texels a lut of this many dimensions and this size holds
  let texelCount = (dims, size) => dims === 1 ? size : dims === 2 ? size*size : size*size*size

  // Settle the size at event time: rounded, at least 2 (so the i/(size-1) domain mapping works),
  // and capped so a 3d lut can't lock the browser up
  let resolveSize = (size, dims) => {
    size = Math.round(size)
    if (!(size >= 2)) { size = defaultSizes[dims] }
    if (texelCount(dims, size) <= maxTexels) { return size }
    let capped = size
    while (texelCount(dims, capped) > maxTexels) { capped = Math.max(2, capped >> 1) }
    consoleOut(`🟠 tex${dims}d size ${size} needs too many texels: using ${capped}`)
    return capped
  }

  // Convert one sampled value to rgba floats. A plain number is a grey, opaque, so tex1d{{x}->x}
  // is an identity ramp rather than a fade; anything else goes through the usual colour conversion
  // so {labh:x}, {h:x} and colour literals all work. colour() returns a shared array: consume it
  // before sampling again.
  let black = {r:0, g:0, b:0, a:1}
  let greyScratch = [0,0,0,1]
  let toRgba = (v) => {
    v = unwrapValue(v)
    if (typeof v !== 'object' || v === null) {
      let g = typeof v === 'number' ? v : 0
      greyScratch[0] = greyScratch[1] = greyScratch[2] = g
      greyScratch[3] = 1
      return greyScratch
    }
    return colour(v, black, 'visualsynth-lut')
  }

  let toByte = (c) => Math.round(Math.max(0, Math.min(1, c)) * 255)

  // Evaluate the arg with the sample coordinates as its positional args, so {x}->, {x,y}-> and
  // {x,y,z}-> all just work (and so does a named function, or a constant). doNotMemoise is
  // essential: the same beat would otherwise memoise the first sample's result across every
  // coordinate (cf play/nodes/nodes.js shaper, source.js and convolver.js, which sample the
  // same way).
  let sampleAt = (arg, x, y, z, e, b) => {
    if (typeof arg === 'function') {
      arg.modifiers = arg.modifiers || {}
      arg.modifiers.value = x
      arg.modifiers.value1 = y
      arg.modifiers.value2 = z
    }
    return evalParamFrame(arg, e, b, {doNotMemoise:true})
  }

  // Sample arg over [0,1]^dims into rgba bytes. x varies fastest, then y, then z: the layout
  // texImage2D/texImage3D expect. The endpoints 0 and 1 are both hit exactly.
  let sampleLut = (arg, dims, size, e, b) => {
    let data = new Uint8Array(texelCount(dims, size) * 4)
    let step = 1 / (size - 1)
    let zn = dims === 3 ? size : 1
    let yn = dims >= 2 ? size : 1
    let at = 0
    for (let k = 0; k < zn; k++) {
      let z = dims === 3 ? k*step : undefined
      for (let j = 0; j < yn; j++) {
        let y = dims >= 2 ? j*step : undefined
        for (let i = 0; i < size; i++) {
          let c = toRgba(sampleAt(arg, i*step, y, z, e, b))
          data[at++] = toByte(c[0])
          data[at++] = toByte(c[1])
          data[at++] = toByte(c[2])
          data[at++] = toByte(c[3])
        }
      }
    }
    return data
  }

  // Upload the sampled data as a texture object shaped for draw/sprite.js. A 1d lut is a size x 1
  // 2d texture (WebGL has no 1d textures); a 3d lut needs the TEXTURE_3D target, which sprite.js
  // reads off .target. Deliberately no width/height: those drive the extents uniform, which only
  // tex{}'s aspect correction wants.
  //
  // The sampled bytes are kept on the texture (with the shape needed to interpret them) rather than
  // discarded after upload: a lut bound for a hub75 display has to be sent over the wire, and the
  // lut's contents never appear in the shader source, so there is nowhere else to recover them from
  // (draw/hub75/PROTOCOL.md §7.2). Cost is bounded by maxTexels above: 4MB worst case, 1-16KB for
  // the default sizes.
  let uploadLut = (data, dims, size) => {
    let gl = system.gl
    let t = { tex: gl.createTexture(), data: data, dims: dims, size: size }
    if (dims === 3) {
      t.target = gl.TEXTURE_3D
      gl.bindTexture(gl.TEXTURE_3D, t.tex)
      gl.texImage3D(gl.TEXTURE_3D, 0, gl.RGBA8, size, size, size, 0, gl.RGBA, gl.UNSIGNED_BYTE, data)
    } else {
      gl.bindTexture(gl.TEXTURE_2D, t.tex)
      gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, size, dims === 1 ? 1 : size, 0, gl.RGBA, gl.UNSIGNED_BYTE, data)
    }
    return t
  }

  // Built once and cached: the key is the parsed arg's own function instance, so editing the px
  // line makes a fresh instance and rebuilds the texture, while a slider or timevar inside the
  // function stays at its build time value. Non-function args (a constant colour) have no useful
  // identity, so they key on their contents instead.
  let byArg = new WeakMap() // arg function -> Map('dims:size' -> texture object)
  let byValue = new Map() // 'dims:size:json' -> texture object
  let lutTexture = (arg, dims, size, e, b) => {
    let key = dims + ':' + size
    let cache
    if (typeof arg === 'function') {
      cache = byArg.get(arg)
      if (cache === undefined) { cache = new Map(); byArg.set(arg, cache) }
    } else {
      cache = byValue
      key += ':' + JSON.stringify(arg === undefined ? null : arg)
    }
    let t = cache.get(key)
    if (t === undefined) {
      t = uploadLut(sampleLut(arg, dims, size, e, b), dims, size)
      cache.set(key, t)
    }
    return t
  }

  // TESTS //
  if ((new URLSearchParams(window.location.search)).get('test') !== null) {

  let assert = (expected, actual) => {
    let x = JSON.stringify(expected)
    let a = JSON.stringify(actual)
    if (x !== a) { console.trace(`Assertion failed.\n>>Expected:\n  ${x}\n>>Actual:\n  ${a}`) }
  }
  // A parsed arg is a function of (event, beat, evalRecurse, modifiers); the sample coordinates
  // arrive as the positional modifiers, exactly as a {x,y,z}-> lambda would see them
  let fn = (f) => (e,b,er,mods) => f(mods.value, mods.value1, mods.value2)
  let ev = {count:0}
  let texel = (data, i) => Array.from(data.slice(i*4, i*4+4))

  // A number is a grey, and stays opaque: tex1d{{x}->x} is an identity ramp
  let ramp = sampleLut(fn(x => x), 1, 3, ev, 0)
  assert(3*4, ramp.length)
  assert([0,0,0,255], texel(ramp, 0)) // Both domain endpoints are hit exactly
  assert([128,128,128,255], texel(ramp, 1))
  assert([255,255,255,255], texel(ramp, 2))

  // Out of range values clamp rather than wrapping round
  let clamped = sampleLut(fn(x => x*3 - 1), 1, 3, ev, 0)
  assert([0,0,0,255], texel(clamped, 0))
  assert([128,128,128,255], texel(clamped, 1))
  assert([255,255,255,255], texel(clamped, 2))

  // An object goes through the usual colour conversion, so colour spaces work
  let col = sampleLut(fn(x => ({r:x, g:0, b:1-x})), 1, 2, ev, 0)
  assert([0,0,255,255], texel(col, 0))
  assert([255,0,0,255], texel(col, 1))
  assert([0,255,0,255], texel(sampleLut(fn(() => ({h:1/3})), 1, 2, ev, 0), 0)) // hsv
  let lab = sampleLut(fn(x => ({labh:x})), 1, 2, ev, 0)
  assert(toByte(0.9582161268492856), lab[0]) // matches colour({labh:0}) in draw/colour.js
  assert(255, lab[3]) // alpha still opaque
  assert([255,0,0,128], texel(sampleLut(fn(() => ({r:1,g:0,b:0,a:1/2})), 1, 2, ev, 0), 0)) // alpha honoured

  // 2d: x varies fastest, then y — the layout texImage2D expects
  let two = sampleLut(fn((x,y) => ({r:x, g:y, b:0})), 2, 2, ev, 0)
  assert(2*2*4, two.length)
  assert([0,0,0,255], texel(two, 0)) // x=0 y=0
  assert([255,0,0,255], texel(two, 1)) // x=1 y=0
  assert([0,255,0,255], texel(two, 2)) // x=0 y=1
  assert([255,255,0,255], texel(two, 3)) // x=1 y=1

  // 3d: and then z slowest
  let three = sampleLut(fn((x,y,z) => ({r:x, g:y, b:z})), 3, 2, ev, 0)
  assert(2*2*2*4, three.length)
  assert([0,0,0,255], texel(three, 0)) // x=0 y=0 z=0
  assert([255,0,0,255], texel(three, 1)) // x=1 y=0 z=0
  assert([0,255,0,255], texel(three, 2)) // x=0 y=1 z=0
  assert([0,0,255,255], texel(three, 4)) // x=0 y=0 z=1
  assert([255,255,255,255], texel(three, 7)) // x=1 y=1 z=1

  // Every sample is evaluated: the arg must not be memoised across coordinates
  let calls = 0
  sampleLut(fn(x => { calls++; return x }), 1, 8, ev, 0)
  assert(8, calls)

  // A constant (non function) arg gives a flat lut rather than blowing up
  assert([255,0,0,255], texel(sampleLut({r:1,g:0,b:0}, 1, 2, ev, 0), 1))
  assert([0,0,0,255], texel(sampleLut(undefined, 1, 2, ev, 0), 0))

  // Sizes: below 2 or unusable falls back to the per-dimension default, and a 3d size that would
  // blow past the texel cap is halved until it fits
  assert(256, resolveSize(undefined, 1))
  assert(64, resolveSize(1, 2))
  assert(16, resolveSize(NaN, 3))
  assert(32, resolveSize(32.4, 1))
  assert(true, texelCount(3, resolveSize(1024, 3)) <= maxTexels)

  console.log('Visual synth lut tests complete')
  }

  return {
    sampleLut: sampleLut,
    lutTexture: lutTexture,
    resolveSize: resolveSize,
    defaultSizes: defaultSizes,
  }
})
